### ISSUE TITLE
Develop python assignment using cmd module (Monday Lecture)

### ISSUE THREAD

**Issue by dimitargnikolov** [cloudmesh/classes#137]
Formulate homework assignment that:

Python module of the week: cmd

Create a python program that has 

```
mycmd deploy: print deploy
mycmd kill: print kill
mycmd benchmark: print benchmark
mycmd report: ...
```

**Comment by miaozhan** [comment]
```
usage syntax:
mycmd <arg>
  <arg> can be:
    deploy         -- simply prints text "deply"
    kill               -- simply prints text "kill"
    benchmark -- simply prints text "benchmark"
    report         -- simply prints text "report"
```

formalize the syntax a bit and unassign myself

**Comment by laszewsk** [comment]
i will create dir in eve repo called

cloudmesh/mycmd

i probably rename soon eve to rest so look for eithe in cloumesh repos

**Comment by laszewsk** [comment]
eve repo has been renamed to rest

**Comment by jemitchell** [comment]
The purpose of this assignment is to familiarize you with the cmd module in python.  cmd module makes command line interfaces in your programs.

Create a python program, which has as its interpreter, mycmd, and develop the following commands:

mycmd deploy: print deploy
mycmd kill: print kill
mycmd benchmark: print benchmark
mycmd report:

usage syntax:

mycmd <arg>
  <arg> can be:
    deploy  -- simply prints text "deploy"
    kill  -- simply prints text "kill"
    benchmark  -- simply prints text "benchmark"
    report  -- simply prints text "report"

In order to achieve your best for more information on the cmd module, refer to: https://pymotw.com/2/cmd/

Also, refer to https://github.com/cloudmesh/rest/tree/master/cloudmesh/command.

**Comment by laszewsk** [comment]
I do not see wher you put this ...

- [ ] where is rst page that contains description about cmd
- [ ] eher eis homework, eg. should be something like Cmd.1 ....
- [ ] have you done video for online students

**Comment by laszewsk** [comment]
here the evidence from newest web page:

cmd  search 
Search Results
Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories.

**Comment by jemitchell** [comment]
I uploaded the cmd.rst file to github. Could someone take  a look before I
link to the page? It is in the lesson repository.

Thanks,
Jerome

**Comment by badi** [comment]
@jemitchell  Did you make a pull request?  I don't see any.

**Comment by dimitargnikolov** [comment]
Added the homework and showed to students on Mon 2/13.
