### ISSUE TITLE
Monday lecture (2/13)

### ISSUE THREAD

**Issue by dimitargnikolov** [cloudmesh/classes#194]
- [x] Python (pygal, cmd) (Dimitar)
- [x] Paper 1 (Dimitar)
- [x] Project (Dimitar, Miao)
- [x] Ansible (Miao)
- [x] Cloudmesh boot vm (Vibhatha)
- [x] Cloudmesh cluster (Vibhatha)
- Issues: 
    - [x] cm sec group (Vibhatha, Tony, Fugang)
    - [x] cm vm ssh, after cluster boot (Tony, Fugang)

**Comment by tonythomascn** [comment]
I've find a way to make cm vm ssh work on my machine. Cheers!

**Comment by laszewsk** [comment]
please document and test on new virtualenv to verify this works. Also document waht needs to change on ~/.cloudmesh/cloudmesh.yaml.

**Comment by tonythomascn** [comment]
It could be a bug. I am not sure about it yet. I will confirm with Fugang.

The situation I met is like this. When I try to execute:

	$ cm vm ssh xl41-0

it automatically match the first public key name rather than the actual key file within the key list. Of course you can’t find the a file with that key name anywhere, because it never exists.

To avoid this, I have to execute:

	$ cm vm ssh xl41-0 —key =~/.ssh/key.pub

to specify the key file I want to use. In this way, I successfully log into my VM on cloud. Also, I believe the —key option only need the physical key file. Even though we already have the key along with its absolute path stored in the key list.

Tony

**Comment by fugangwang** [comment]
I updated the published cloudmesh client documentation to reflect the current 'cm secgroup' usage and functionality. Please try and let me know if you see problems.

**Comment by fugangwang** [comment]
For 'vm ssh', I believe you have to set a default key to use (to verify, use 'cm info'). Otherwise it may grab the first key from the keys list to try. You can always specify a key with '--key' parameter as Tony does.

**Comment by vibhatha** [comment]
Cloudmesh Client installation task was completed. 
Video was uploaded to Youtube channel.

https://youtu.be/R50IQYhr-vg?t=3

**Comment by dimitargnikolov** [comment]
Closing this and will add a separate entry for next week based on what we discussed on Tue, Feb 21.
