### ISSUE TITLE
Stduent: Investigation of pull request 95

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/classes#96]
We need to investigate pull request:
https://github.com/cloudmesh/classes/pull/95

**Comment by naveenkumar2703** [comment]
Pull request and commits were created, since I was trying to use git
hub desktop instead of command line interface. It created four remote
servers instead of two by default. That commit and pull request are not
required. I have already discarded the whole '.git' clone and created a new
one. I have also created a separate pull request. I'm looking for a way to
revert back that unwanted commit.

**Comment by laszewsk** [comment]
This seems to have been resolved with latests pull request
